name: flutter_instance_manager
description: A plugin that provides a mechanism to sync objects between Dart and native code.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  plugin_platform_interface: ^2.0.2
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  pigeon: ^11.0.1
  
flutter:
  plugin:
    platforms:
      android:
        package: com.baseflow.instancemanager
        pluginClass: FlutterInstanceManagerPlugin
