// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by InstanceManagerHostApi.
NSObject<FlutterMessageCodec> *InstanceManagerHostApiGetCodec(void);

/// Host API for managing the native `InstanceManager`.
@protocol InstanceManagerHostApi
/// Clear the native `InstanceManager`.
///
/// This is typically only used after a hot restart.
- (void)clearWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void InstanceManagerHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<InstanceManagerHostApi> *_Nullable api);

/// The codec used by JavaObjectHostApi.
NSObject<FlutterMessageCodec> *JavaObjectHostApiGetCodec(void);

/// Handles methods calls to the native Java Object class.
///
/// Also handles calls to remove the reference to an instance with `dispose`.
///
/// See https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html.
@protocol JavaObjectHostApi
- (void)disposeIdentifier:(NSString *)identifier error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void JavaObjectHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<JavaObjectHostApi> *_Nullable api);

/// The codec used by JavaObjectFlutterApi.
NSObject<FlutterMessageCodec> *JavaObjectFlutterApiGetCodec(void);

/// Handles callbacks methods for the native Java Object class.
///
/// See https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html.
@interface JavaObjectFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)disposeIdentifier:(NSString *)identifier completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
